services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: poza_nuta
      POSTGRES_PASSWORD: poza_nuta
      POSTGRES_DB: poza_nuta
    ports:
      - "5432:5432"
    volumes:
      - poza_nuta_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poza_nuta -d poza_nuta"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  poza_nuta_postgres_data:
